Fix  'INDEX_NOT_EXIST' does not exist in Milvus_Upsert.ts
nodes/vectorstores/Milvus/Milvus_Upsert.ts(255,59): error TS2551: Property 'INDEX_NOT_EXIST' does not exist on type 'typeof ErrorCode'. Did you mean 'IndexNotExist'?